### PR TITLE
Ignore gcc 8 warnings.

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**
Same as #33 but ignore warning instead of "fixing" it.

### CODE REVIEW

**Comment by mclow** [comment]
I'm fine with this; thanks.

**Comment by eldiener** [comment]
Is gcc8 available on any Ljnux OSs ? I can not test this because even Fedora 27 has 7.3 as the latest gcc and mingw-64 has gcc 7.2 as the latest gcc..

**Comment by Romain-Geissler-1A** [comment]
I doubt you will find it in any stable distribution right now given that officially gcc 8 is not even released (will be at some point in April 2018). In my company we compile it ourselves.

This page seems to hint that Fedora 28 (currently rawhide) has it already: https://apps.fedoraproject.org/packages/gcc

**Comment by Romain-Geissler-1A** [comment]
Note that in #31 some continuous build system is mentioned, so that may be for you an easier way you to validate this pull request actually silences the warning, rather than having to setup a unstable Fedora 28.

**Comment by Romain-Geissler-1A** [comment]
It is available in Debian testing as well (it's not the default "gcc" package, but you can install "gcc-8" instead): https://packages.debian.org/buster/gcc-8

**Pull request merged**
