### PR TITLE
Fix to Ticket #11001

### PR DESCRIPTION
**Pull request by brunocodutra**
According to reference, insert_range should work for any Extensible
sequence or Extensible Associative sequence, but the default
implementation of insert_range_impl assumes a front_inserter is defined
for the given sequence, but neither Extensible nor every Extensible
Associative sequences are required to also be a Front Extensible
sequence. This fix rely only on insert, which is defined for every
Extensible sequence.

### CODE REVIEW

**Comment by brunocodutra** [comment]
Taking a closer look at the documentation, I came to realise that order does naturally matters for a generic Extensible sequence and indeed insering elements in the end of a list has linear time complexity, while it is constant when inserting at the beginning.

I thus believe it would be better to implement insert_range by means of reverse_fold, hence always inserting elements at the beginning.

Later this evening I believe I could take a look at this and update the pull request.

**Comment by brunocodutra** [comment]
Just like for insert, the second parameter of insert_range, Pos, doesn't really mean anything for associative sequences and is essentially ignored. To my understanding, the code and documentation should be updated to reflect this fact. I volunteer to do the job, but I don't think these changes fit the scope of this pull request, since in fact it consists in a new feature, so I plan to open a new request just for that.

**Comment by brunocodutra** [comment]
All mpl tests were verified to pass for clang 3.6 and gcc 4.9.2 on linux and for msvc 2010 on windows xp

**Comment by eldiener** [comment]
This looks good and has been locally tested with all tests passing, so I am going to merge to develop. Please check the 'develop' regression tests to make sure there is no errors being caused by this fix.

**Comment by brunocodutra** [comment]
Thank you Edward, I'll watch the test reports for anything suspicious.

**Pull request merged**
