### PR TITLE
Fixed a bug with the template substitution adding temporary string

### PR DESCRIPTION
**Pull request by amarzial**
(e.g.) with i = 110 the script created 10100 instead:
line = re.sub(r'20', re.escape(str(i+10)), line.rstrip())
    20 -> 110
line = re.sub(r'11', re.escape(str(i + 1)), line.rstrip())
    110 -> 1010
line = re.sub(r'10(?![0-9])', re.escape(str(i)), line.rstrip())
    1100 -> 10100

### CODE REVIEW

**Comment by eldiener** [comment]
I think you mean with i = 100, not 110, in your comment. As in:

(e.g.) with i = 100 the script created 10100 instead:
line = re.sub(r'20', re.escape(str(i+10)), line.rstrip())
20 -> 110
line = re.sub(r'11', re.escape(str(i + 1)), line.rstrip())
110 -> 1010
line = re.sub(r'10(?![0-9])', re.escape(str(i)), line.rstrip())
1010 -> 10100

**Comment by Bagira80** [comment]
I think your example has some typos but I think I understand what kind of problem it solves.

In your example you probably meant generating (at least) `110` elements which will eventually result in `i = 100` which again results in

* `20` being replaced by `110`,
* `11` being replaced by `101`, which also replaces the first substitution from `110` to `1010` and
* alone-standing `10` being replaced by `100`, which again replaces the second substitution from `1010` to `10100`.

(You are probably the first to try to generate more than 100 elements, because nobody else reported this error. :-) )

Probably, someone of the *Boost Community Maintenance* team ( @eldiener ?) can merge this pull-request?

**Comment by Bagira80** [comment]
:-) I realize, Edward was faster responding than me typing my response.
Thanks for merging, Edward.

**Comment by amarzial** [comment]
True, sorry.
Basically it happens at i=100 every time you put a value bigger than 100 on
the command line arguments

Il 10 lug 2017 18:18, "Edward Diener" <notifications@github.com> ha scritto:

**Pull request merged**
